DP-1946
holidayextras/jsonschema-bigquery pull request #1
Opened 2018-10-18 15:50 UTC by michaelsmithhx

GBQ integration and includes a fix for optional arrays so that items like user tags generate correctly

2018-10-18 23:53 UTC, hx-markterry requested changes
Nice work on getting the allOf working, only a few comments and need to revert most of the example changes.

2018-10-18 23:53 UTC, hx-markterry commented on src/test.json
> +                    "type": "string"
indentation is wrong here

2018-10-18 23:53 UTC, hx-markterry commented on README.md
> -    const jsonSchemaBigquery = require('jsonschema-bigquery')
Can you keep these code blocks as i see the modules primary function is to allow json schema to converted programmatically. The JSBQ command is an added extra.

2018-10-18 23:53 UTC, hx-markterry commented on package.json
> +    "eslint": "5.6.1",
Can you add `^` to the versions please.

2018-10-18 23:53 UTC, hx-markterry commented on package.json
> +    "lint": "eslint ."
This should of been done in a separate PR.

Don't forget this is not a HX project so changing/applying linting on someone else project is a bit intrusive.

2018-10-18 23:53 UTC, hx-markterry commented on src/index.js
> +jsonSchemaBigquery._isRepeated = (schema) => schema.type === 'array' || (Array.isArray(schema.type) && schema.type.includes('array'))
Do we have any schemas where we have array of types, which include arrays?

2018-10-18 23:53 UTC, hx-markterry commented on src/jsbq.js
> +  tableOptions.timePartitioning = {
We need to mention this behaviour in the docs as other users will need to be aware of it.

2018-10-18 23:53 UTC, hx-markterry commented on test/samples/allOf/input.json
> +    "allOf": [
The next example covers this already, don't need to add allof here.

2018-10-18 23:53 UTC, hx-markterry commented on test/samples/anyOfMultipleTypes/input.json
> +    "allOf": [
The example above covers this already, don't need to add allof here.

2018-10-18 23:53 UTC, hx-markterry commented on test/samples/complex/input.json
> +    "allOf": [
We dont need to add allOf here as we have other examples that do this, can we revert this please.

2018-10-18 23:53 UTC, hx-markterry commented on test/samples/fieldDescription/input.json
> +    "allOf": [
We dont need to add allOf here as we have other examples that do this, can we revert this please.

2018-10-18 23:53 UTC, hx-markterry commented on test/samples/nestedRepeated/input.json
> +    "allOf": [
We dont need to add allOf here as we have other examples that do this, can we revert this please.

2018-10-18 23:53 UTC, hx-markterry commented on test/samples/nullable/input.json
> +    "allOf": [
We dont need to add allOf here as we have other examples that do this, can we revert this please.

2018-10-18 23:53 UTC, hx-markterry commented on test/samples/repeated/input.json
> +    "allOf": [
We dont need to add allOf here as we have other examples that do this, can we revert this please.

2018-10-18 23:53 UTC, hx-markterry commented on test/samples/simple/input.json
> +    "allOf": [
We dont need to add allOf here as we have other examples that do this, can we revert this please.

2018-10-18 23:53 UTC, hx-markterry commented on test/samples/timestamp/input.json
> +    "allOf": [
We dont need to add allOf here as we have other examples that do this, can we revert this please.

2018-10-18 23:53 UTC, hx-markterry commented on test/samples/typeArray/input.json
> +    "allOf": [
We dont need to add allOf here as we have other examples that do this, can we revert this please.

2018-10-18 23:53 UTC, hx-markterry commented on README.md
> +Note that some features involve bespoke interpretation of schema details suited to our environment.
Can we list any specifics here?

2018-10-22 11:22 UTC, michaelsmithhx commented
Closing as new PR will introduce the cloned bigjson.py logic

2018-10-22 11:50 UTC, closed without merging